### ISSUE TITLE
Proxychains won't work anymore

### ISSUE THREAD

**Issue by wirehack7** [Cleveridge/cleveridge-ssh-scanner#2]
I am trying to route the traffic to the local TOR proxy as described in the README, but the traffic won't routed through it.

```proxychains4 ./cl_ssh_scan.py```

```
Your IP [78.46.*.*] :
Local IP : 78.46.*.*
Visible IP : 78.46.*.*
   Break up - visible !!!

   Add 'Socks4 127.0.0.1 9050' to /etc/proxychains.conf.
   Start Tor service, then
   proxychains ./cl_ssh_scan.py
```

Proof that proxychains4 is working:
```
$: curl ifconfig.io
78.46.*.*
$: proxychains4 curl ifconfig.io
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.8.1-git-11-gba61b48
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  ifconfig.io:80  ...  OK
80.82.64.29
```

It seems for me like an issue with Python and proxychains4.

**Comment by Cleveridge** [comment]
Thanks for the feedback. 
I used proxychains 3.1 for it. I'll take a look at it as soon as possible and I 'll keep you informed.

**Comment by wirehack7** [comment]
Seems proxychains is completely broken if python is not compiled with musl etc. 
So maybe best resolution will be using proxy directly in python. As config like the external ip I assume. 

https://github.com/rofl0r/proxychains-ng/issues/55

**Comment by Cleveridge** [comment]
With the new V0.04 build 12 I removed the 'break up' when the user ip was visible. Now the scanner only warns the user when the user ip is visible.
